# Generated by Django 4.2.25 on 2025-11-03 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('area', models.FloatField(verbose_name='Площадь (м²)')),
                ('rooms', models.PositiveIntegerField(verbose_name='Количество комнат')),
                ('type', models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Аренда')], default='sale', max_length=10, verbose_name='Тип')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('sold', 'Продано'), ('rented', 'Сдано в аренду'), ('archived', 'В архиве')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимость',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='Изображение')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Изображение недвижимости',
                'verbose_name_plural': 'Изображения недвижимости',
            },
        ),
    ]
