# Generated by Django 5.2.7 on 2025-11-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_contactrequest_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="boiler_type",
            field=models.CharField(
                choices=[
                    ("none", "Нет"),
                    ("factory", "Заводской"),
                    ("custom", "Самодельный"),
                ],
                default="none",
                max_length=10,
                verbose_name="Тип котла",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="gender_preference",
            field=models.CharField(
                choices=[
                    ("any", "Всем"),
                    ("male", "Парням"),
                    ("female", "Девушкам"),
                    ("family", "Семейным"),
                ],
                default="any",
                max_length=10,
                verbose_name="Кому сдается",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="has_furniture",
            field=models.BooleanField(default=False, verbose_name="С мебелью"),
        ),
        migrations.AddField(
            model_name="property",
            name="near_university",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Рядом с университетом"
            ),
        ),
    ]
