# Generated by Django 5.2.7 on 2025-11-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_property_boiler_type_property_gender_preference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="gender_preference",
            field=models.CharField(
                choices=[
                    ("any", "Всем"),
                    ("male", "Парням"),
                    ("female", "Девушкам"),
                    ("family", "Семейным"),
                    ("military", "Военным"),
                ],
                default="any",
                max_length=10,
                verbose_name="Кому сдается",
            ),
        ),
    ]
