# Generated by Django 5.2.7 on 2025-11-05 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_alter_property_gender_preference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="apartment_number",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Номер квартиры"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="building_type",
            field=models.CharField(
                choices=[
                    ("apartment", "Многоквартирный дом"),
                    ("private", "Частный дом"),
                ],
                default="apartment",
                max_length=20,
                verbose_name="Тип здания",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="building_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Год постройки"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="entrance",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Подъезд"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="floor",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="На каком этаже находится квартира",
                null=True,
                verbose_name="Этаж",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="has_balcony",
            field=models.BooleanField(default=False, verbose_name="Есть балкон"),
        ),
        migrations.AddField(
            model_name="property",
            name="has_conditioner",
            field=models.BooleanField(default=False, verbose_name="Есть кондиционер"),
        ),
        migrations.AddField(
            model_name="property",
            name="has_elevator",
            field=models.BooleanField(default=False, verbose_name="Есть лифт"),
        ),
        migrations.AddField(
            model_name="property",
            name="has_fridge",
            field=models.BooleanField(default=False, verbose_name="Есть холодильник"),
        ),
        migrations.AddField(
            model_name="property",
            name="has_parking",
            field=models.BooleanField(default=False, verbose_name="Есть парковка"),
        ),
        migrations.AddField(
            model_name="property",
            name="has_washing_machine",
            field=models.BooleanField(
                default=False, verbose_name="Есть стиральная машина"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="has_wifi",
            field=models.BooleanField(default=False, verbose_name="Есть WiFi"),
        ),
        migrations.AddField(
            model_name="property",
            name="nearby_landmarks",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Автоматически заполняется: [{"name": "НГПИ", "distance": 1.2}]',
                verbose_name="Ближайшие ориентиры",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="pets_allowed",
            field=models.BooleanField(default=False, verbose_name="Можно с животными"),
        ),
        migrations.AddField(
            model_name="property",
            name="repair_type",
            field=models.CharField(
                choices=[
                    ("no", "Без ремонта"),
                    ("cosmetic", "Косметический"),
                    ("euro", "Евроремонт"),
                    ("designer", "Дизайнерский"),
                ],
                default="no",
                max_length=20,
                verbose_name="Ремонт",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="search_keywords",
            field=models.TextField(
                blank=True,
                help_text="Автоматически генерируется из адреса и описания",
                verbose_name="Ключевые слова для поиска",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="total_floors",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Сколько этажей в доме",
                null=True,
                verbose_name="Всего этажей",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["latitude", "longitude"], name="properties__latitud_6eb2b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["type", "status"], name="properties__type_d3d96a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["gender_preference"], name="properties__gender__4dbfb3_idx"
            ),
        ),
    ]
