# Generated by Django 5.2.7 on 2025-11-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0007_property_apartment_number_property_building_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="type",
            field=models.CharField(
                choices=[
                    ("sale", "Продажа"),
                    ("rent", "Аренда"),
                    ("daily_rent", "Посуточная аренда"),
                ],
                default="sale",
                max_length=15,
                verbose_name="Тип",
            ),
        ),
    ]
