# Generated by Django 5.2.7 on 2025-11-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_alter_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="price_per_day",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена за сутки",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="price_per_month",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена за месяц",
            ),
        ),
    ]
