# Generated by Django 5.2.7 on 2025-11-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0009_property_price_per_day_property_price_per_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="min_rental_days",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Для посуточной: минимум сколько суток. Для долгосрочной: минимум месяцев",
                verbose_name="Минимальный срок аренды",
            ),
        ),
    ]
