# Generated by Django 5.2.8 on 2025-11-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_property_min_rental_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='gender_preference',
            field=models.JSONField(blank=True, default=list, help_text='Можно выбрать несколько вариантов', verbose_name='Кому сдается'),
        ),
    ]
