# Generated by Django 5.1.4 on 2025-11-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0011_alter_property_gender_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Цена",
            ),
        ),
    ]
