# Generated by Django 5.1.4 on 2025-12-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0012_alter_property_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="price_per_day",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Цена за сутки",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="price_per_month",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Цена за месяц",
            ),
        ),
    ]
