# Generated by Django 4.2.25 on 2025-11-03 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('mortgages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgages', to='users.user', verbose_name='Пользователь'),
        ),
    ]
