# Generated by Django 4.2.25 on 2025-11-03 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('auctions', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='users.user', verbose_name='Участник'),
        ),
        migrations.AddField(
            model_name='auction',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_auctions', to='users.user', verbose_name='Организатор'),
        ),
        migrations.AddField(
            model_name='auction',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='properties.property', verbose_name='Недвижимость'),
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to='users.user', verbose_name='Победитель'),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('auction', 'bidder', 'amount')},
        ),
    ]
