# Generated by Django 5.1.4 on 2025-11-19 05:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="end_type",
            field=models.CharField(
                choices=[
                    ("time", "По времени"),
                    ("price", "По цене"),
                    ("both", "По времени или цене"),
                ],
                default="time",
                max_length=20,
                verbose_name="Тип окончания",
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Оплачен"),
        ),
        migrations.AddField(
            model_name="auction",
            name="payment_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50000.00"),
                max_digits=10,
                verbose_name="Сумма оплаты",
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Ожидает оплаты"),
                    ("scheduled", "Запланирован"),
                    ("active", "Активен"),
                    ("completed", "Завершен"),
                    ("cancelled", "Отменен"),
                ],
                default="pending_payment",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="target_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Целевая цена",
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AddField(
            model_name="auction",
            name="winning_bid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_auction",
                to="auctions.bid",
                verbose_name="Победная ставка",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время окончания"
            ),
        ),
        migrations.CreateModel(
            name="AuctionPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50000.00"),
                        max_digits=10,
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "click_trans_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Click Transaction ID",
                    ),
                ),
                (
                    "click_paydoc_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Click Paydoc ID",
                    ),
                ),
                (
                    "merchant_trans_id",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Merchant Transaction ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("processing", "В обработке"),
                            ("completed", "Завершен"),
                            ("failed", "Не удался"),
                            ("cancelled", "Отменен"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "error_note",
                    models.TextField(
                        blank=True, null=True, verbose_name="Примечание об ошибке"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "auction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="auctions.auction",
                        verbose_name="Аукцион",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auction_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж аукциона",
                "verbose_name_plural": "Платежи аукционов",
                "ordering": ["-created_at"],
            },
        ),
    ]
