# Generated by Django 5.2.7 on 2025-12-08 09:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_end_type_auction_is_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=10, verbose_name='Сумма оплаты')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='payment_screenshots/', verbose_name='Скриншот оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает загрузки скриншота'), ('waiting_confirmation', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=25, verbose_name='Статус')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID сообщения в Telegram')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Причина отклонения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_payment', to='auctions.auction', verbose_name='Аукцион')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ручной платеж',
                'verbose_name_plural': 'Ручные платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
